version: '3'
services:
  sprio-elk:
    image: "sebp/elk:es232_l232_k450"
    ports:
        - "5601:5601"
        - "10042:10042/udp"
    volumes:
      - "elk-data:/var/lib/elasticsearch"
      - "./logstash-input.conf:/etc/logstash/conf.d/03-logstash-input.conf:ro" 
      - "./logstash-output.conf:/etc/logstash/conf.d/30-output.conf:ro" 
volumes:
    elk-data:

